import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Toaster} from "sonner";
import "sonner/dist/styles.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import {MusicPlayerProvider} from "@/context/MusicPlayerContext";
import GlobalPlayer from "@/components/GlobalPlayer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body suppressHydrationWarning className="min-h-full flex flex-col">
        <ReactQueryProvider>
            <MusicPlayerProvider>
                {children}
                <Toaster
                    position="top-right"
                    richColors
                    closeButton
                    theme="dark"
                    toastOptions={{
                        style: {
                            background: "#0f90b4",
                            border: "1px solid rgba(162, 89, 255, 0.35)",
                            color: "#f3f3ff",
                        },
                    }}
                />
                <GlobalPlayer/>
            </MusicPlayerProvider>
        </ReactQueryProvider>
        </body>
        </html>
    );
}
